#!/usr/bin/env bash
# Tiny colored fetch script
# Requires Typicons Font to display the icons
# elenapan @ github
# sioodmy @ github

f=3 b=4
for j in f b; do
  for i in {0..7}; do
    printf -v $j$i %b "\e[${!j}${i}m"
  done
done
d=$'\e[1m'
t=$'\e[0m'
v=$'\e[7m'

# Items
h=wm

k=kr
kernel="$(uname -r | cut -d '-' -f1)"

sh=sh
shell=$(basename $SHELL)

. /etc/os-release
o=os
os="$ID $VERSION_ID"

colors=$(for i in {0..7}; do echo -en "\e[${1}$((30 + $i))m▁▁▁"; done)

# (\ /)
# ( · ·)
# c(")(")

# (\ /)
# ( . .)
# c(")(")

cat <<EOF

  (\ /)    $f6$o $t~ $os
  ( $d· ·$t)  $f6 $k $t~ $kernel
  c($f1"$t)($f1"$t)  $f6$sh $t~ $shell
  $colors
 
EOF
