_: {
  home.persistence."/persist/home/sioodmy" = {
    allowOther = true;
    directories = [
      "download"
      "music"
      "dev"
      "docs"
      "pics"
      ".keepass"
      "vids"
      "other"
      ".ssh"
      ".keepass"
      ".local/share/direnv"
      ".cache/tealdeer"
      ".local/share/distrobox"
      ".cache/containers"
      ".config/syncthing"
      ".cache/flutter"
      ".local/share/PrismLauncher"
      ".local/share/TelegramDesktop"
      ".local/share/keyrings"
      ".config/Caprine"
      ".cache/keepassxc"
      ".config/WebCord"
      ".config/BraveSoftware/"
      ".config/spotify-tui"
      ".cache/BraveSoftware/"
      ".cache/nix"
      ".cache/chromium"
      ".config/chromium"
      ".cache/thunderbird/"
      ".thunderbird"
      ".cache/spotifyd"
      ".config/spotify"
      ".cache/starship"
      ".local/share/nheko"
      ".cache/nheko"
      ".config/nheko"
      ".cache/nix-index"
      ".config/obs-studio"
      ".mozilla"
      ".cache/mozilla"
    ];
  };
}
