# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nord-nvim = {
    pname = "nord-nvim";
    version = "c88388b2a5f6e621df2718c316b856d4971bb89d";
    src = fetchFromGitHub {
      owner = "andersevenrud";
      repo = "nordic.nvim";
      rev = "c88388b2a5f6e621df2718c316b856d4971bb89d";
      fetchSubmodules = false;
      sha256 = "sha256-ipmt0xD2zTfoh8fyYG4+09uVL2ef98FE9VwWpWJtQks=";
    };
    date = "2024-06-16";
  };
}
