# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wallpapers = {
    pname = "wallpapers";
    version = "47a9b2fa004266191737d22899acc0eb410e946b";
    src = fetchFromGitHub {
      owner = "sioodmy";
      repo = "wallpapers";
      rev = "47a9b2fa004266191737d22899acc0eb410e946b";
      fetchSubmodules = false;
      sha256 = "sha256-yU/cF+w40Eo4l6kfJd/oC4Gfna0DBSZmfPEgO7z4UpE=";
    };
    date = "2025-03-09";
  };
}
