# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wallpapers = {
    pname = "wallpapers";
    version = "762c067796b6a4fddc6b8d051e70844d1701f1b7";
    src = fetchFromGitHub {
      owner = "sioodmy";
      repo = "wallpapers";
      rev = "762c067796b6a4fddc6b8d051e70844d1701f1b7";
      fetchSubmodules = false;
      sha256 = "sha256-Er+ZnJIcRSYmsDkFyttJN6KdDxn4PVgfrkoXgrHzFyA=";
    };
    date = "2025-01-08";
  };
}
