#!/bin/sh
# window "swallow" for Niri
# (https://github.com/YaLTeR/niri/discussions/762)
#
# this script shrinks the terminal into a column with the new window,
# incredibly hacky technique
#
# usage: niri-swal.sh mpv video.mp4
#
# useful to bind in your shell.

set -e

TERM_ID=$(niri msg focused-window | head -n 1 | grep -o '[0-9]*')

$@ &
# may need to adjust this
sleep 0.5

niri msg action focus-window --id "$TERM_ID"
niri msg action consume-window-into-column
niri msg action move-window-down
niri msg action set-window-height --id "$TERM_ID" 0%
niri msg action focus-window-up

wait
niri msg action set-window-height --id "$TERM_ID" 100%
