# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  incline = {
    pname = "incline";
    version = "16fc9c073e3ea4175b66ad94375df6d73fc114c0";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "incline.nvim";
      rev = "16fc9c073e3ea4175b66ad94375df6d73fc114c0";
      fetchSubmodules = false;
      sha256 = "sha256-5DoIvIdAZV7ZgmQO2XmbM3G+nNn4tAumsShoN3rDGrs=";
    };
    date = "2024-05-16";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "2fdd4e53286dbb8978699b5e1cd09835362a70f3";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "2fdd4e53286dbb8978699b5e1cd09835362a70f3";
      fetchSubmodules = false;
      sha256 = "sha256-Hs272gEgYj29XJ4FnMRXExtnbYqRGXIGaRZXo9I2P58=";
    };
    date = "2025-02-09";
  };
  org-bullets = {
    pname = "org-bullets";
    version = "21437cfa99c70f2c18977bffd423f912a7b832ea";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "org-bullets.nvim";
      rev = "21437cfa99c70f2c18977bffd423f912a7b832ea";
      fetchSubmodules = false;
      sha256 = "sha256-/l8IfvVSPK7pt3Or39+uenryTM5aBvyJZX5trKNh0X0=";
    };
    date = "2025-01-23";
  };
  org-checkbox = {
    pname = "org-checkbox";
    version = "d33464548b7c743c6ca12c3ac0712573e3964daa";
    src = fetchFromGitHub {
      owner = "massix";
      repo = "org-checkbox.nvim";
      rev = "d33464548b7c743c6ca12c3ac0712573e3964daa";
      fetchSubmodules = false;
      sha256 = "sha256-fN6zEBPPQl8eXhWugkxFp++vW/acWviKvFRr1cNcu/A=";
    };
    date = "2024-02-25";
  };
  org-modern = {
    pname = "org-modern";
    version = "c024900b7ee78a0274036025569b47001ef3e6aa";
    src = fetchFromGitHub {
      owner = "danilshvalov";
      repo = "org-modern.nvim";
      rev = "c024900b7ee78a0274036025569b47001ef3e6aa";
      fetchSubmodules = false;
      sha256 = "sha256-TYs3g5CZDVXCFXuYaj3IriJ4qlIOxQgArVOzT7pqkqs=";
    };
    date = "2023-05-12";
  };
  orgmode = {
    pname = "orgmode";
    version = "af90f8f8146fd56d9f7d0f0862b07a1c5c01cd6c";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "orgmode";
      rev = "af90f8f8146fd56d9f7d0f0862b07a1c5c01cd6c";
      fetchSubmodules = false;
      sha256 = "sha256-aob892QYPC45BilrDsabkfhp3xt+VXHpmTHSWp2tNuY=";
    };
    date = "2025-02-09";
  };
  scope = {
    pname = "scope";
    version = "e1799fa37178382fc228245c41af5547e3f95182";
    src = fetchFromGitHub {
      owner = "tiagovla";
      repo = "scope.nvim";
      rev = "e1799fa37178382fc228245c41af5547e3f95182";
      fetchSubmodules = false;
      sha256 = "sha256-rOuEDd90dMRCa+zikTQdE+D4rpx4PFmsk8JpvjK1b7E=";
    };
    date = "2024-12-20";
  };
  sixelpreview = {
    pname = "sixelpreview";
    version = "6292991a005e1a367095f4d404405a626c82b49f";
    src = fetchFromGitHub {
      owner = "sioodmy";
      repo = "sixelpreview.nvim";
      rev = "6292991a005e1a367095f4d404405a626c82b49f";
      fetchSubmodules = false;
      sha256 = "sha256-0jwSRuLHSHzeCKk+EdyhhlNLsZYRfJI6hxW4UCNn3uc=";
    };
    date = "2024-08-11";
  };
}
