# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  incline = {
    pname = "incline";
    version = "16fc9c073e3ea4175b66ad94375df6d73fc114c0";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "incline.nvim";
      rev = "16fc9c073e3ea4175b66ad94375df6d73fc114c0";
      fetchSubmodules = false;
      sha256 = "sha256-5DoIvIdAZV7ZgmQO2XmbM3G+nNn4tAumsShoN3rDGrs=";
    };
    date = "2024-05-16";
  };
  neotree = {
    pname = "neotree";
    version = "a77af2e764c5ed4038d27d1c463fa49cd4794e07";
    src = fetchFromGitHub {
      owner = "nvim-neo-tree";
      repo = "neo-tree.nvim";
      rev = "a77af2e764c5ed4038d27d1c463fa49cd4794e07";
      fetchSubmodules = false;
      sha256 = "sha256-Lqt0KJNT9HmpJwZoWChYeVBrDWhscRe8COqVCwgcTwk=";
    };
    date = "2024-09-16";
  };
  nvim-base-16 = {
    pname = "nvim-base-16";
    version = "6ac181b5733518040a33017dde654059cd771b7c";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "nvim-base16";
      rev = "6ac181b5733518040a33017dde654059cd771b7c";
      fetchSubmodules = false;
      sha256 = "sha256-GRF/6AobXHamw8TZ3FjL7SI6ulcpwpcohsIuZeCSh2A=";
    };
    date = "2024-05-23";
  };
  scope = {
    pname = "scope";
    version = "932102696ead2b7ab9ff65017767b57e2722fdde";
    src = fetchFromGitHub {
      owner = "tiagovla";
      repo = "scope.nvim";
      rev = "932102696ead2b7ab9ff65017767b57e2722fdde";
      fetchSubmodules = false;
      sha256 = "sha256-2eM+KXsF66ocdaV4zVHy8afgP1v+Gj85R3XBhmDORtU=";
    };
    date = "2024-09-17";
  };
  sixelpreview = {
    pname = "sixelpreview";
    version = "6292991a005e1a367095f4d404405a626c82b49f";
    src = fetchFromGitHub {
      owner = "sioodmy";
      repo = "sixelpreview.nvim";
      rev = "6292991a005e1a367095f4d404405a626c82b49f";
      fetchSubmodules = false;
      sha256 = "sha256-0jwSRuLHSHzeCKk+EdyhhlNLsZYRfJI6hxW4UCNn3uc=";
    };
    date = "2024-08-11";
  };
  telescope-orgmode = {
    pname = "telescope-orgmode";
    version = "2cd2ea778726c6e44429fef82f23b63197dbce1b";
    src = fetchFromGitHub {
      owner = "nvim-orgmode";
      repo = "telescope-orgmode.nvim";
      rev = "2cd2ea778726c6e44429fef82f23b63197dbce1b";
      fetchSubmodules = false;
      sha256 = "sha256-yeGdy1aip4TZKp++MuSo+kxo+XhFsOT0yv+9xJpKEps=";
    };
    date = "2024-08-01";
  };
}
