{
  pkgs,
  inputs,
  ...
}: let
  inherit (builtins) attrValues;
in {
  environment.systemPackages =
    attrValues {
      inherit
        (pkgs)
        clang-tools
        bear
        niri
        audacity
        geteduroam-cli
        libreoffice-qt6-fresh
        ttyper
        pavucontrol
        librewolf
        grim
        slurp
        wl-clipboard
        quickshell
        mpv
        tdesktop
        flare-signal
        vencord
        evolution
        rnote
        caprine
        ytmdl
        swaybg
        yt-dlp
        transmission_4-gtk
        nicotine-plus
        imv
        signal-desktop
        vesktop
        gimp3
        inkscape
        keepassxc
        clang
        gnumake
        cargo
        go
        gcc
        git
        ripgrep
        zoxide
        fzf
        eza
        gping
        dogdns
        onefetch
        cpufetch
        microfetch
        tealdeer
        glow
        hyperfine
        imagemagick
        ffmpeg-full
        nmap
        xh
        grex
        jq
        rsync
        figlet
        qrencode
        unzip
        ;
    } ++ [ inputs.helium-browser.packages."${pkgs.system}".helium];
}
